# @package _group_
anchor_generator_class: CylidricalAnchorGeneratorRange
sizes: [1.6, 3.9, 1.56] #original [1.6, 3.9, 1.56] # custom 1 [3.9, 1.56, 1.6] 
feature_map_size: [1, 80, 176] # z, y, x
anchor_ranges: [0, -1.0471975511965976, -1.0, 80.0, 1.0471975511965976, -1.0] #[0, -40.0, -3.0, 70.4, 40, 1.0]
rotations: [0, 1.57]
matched_threshold: 0.6
unmatched_threshold: 0.45